"""Integration and analytical tests for spatial axis contract and physics operator alignment."""

import os
import h5py
import numpy as np
import pytest
import torch

from src.data.shear_flow_dataset import ShearFlowDataset
from src.utils.fft_derivatives import (
    spectral_grad_2d,
    spectral_grad_xy,
    compute_divergence,
    compute_vorticity,
    compute_laplacian_2d,
)
from src.losses.divergence import DivergenceLoss
from src.losses.vorticity import VorticityLoss


def test_synthetic_hdf5_dataset_axis_contract(tmp_path):
    """Test 1: Verify synthetic HDF5 with shape (..., Nx=64, Ny=128) outputs (..., C, Nx, Ny)."""
    h5_path = tmp_path / "shear_flow_Reynolds_1e4_Schmidt_1e-1.hdf5"
    nx, ny = 64, 128
    t_steps = 10

    # Create synthetic HDF5 matching The Well shear_flow schema
    with h5py.File(h5_path, "w") as f:
        # dimensions
        f.create_dataset("dimensions/time", data=np.linspace(0, 1, t_steps))
        f.create_dataset("dimensions/x", data=np.linspace(0, 1, nx))
        f.create_dataset("dimensions/y", data=np.linspace(0, 1, ny))

        # Distinct spatial patterns: x gradient for u, y gradient for v
        x = np.linspace(0, 1, nx)[:, None]
        y = np.linspace(0, 1, ny)[None, :]
        u_field = np.broadcast_to(np.sin(2 * np.pi * x), (1, t_steps, nx, ny))
        v_field = np.broadcast_to(np.cos(2 * np.pi * y), (1, t_steps, nx, ny))
        vel = np.stack([u_field, v_field], axis=-1).astype(np.float32)

        f.create_dataset("t1_fields/velocity", data=vel)
        f.create_dataset("t0_fields/pressure", data=np.zeros((1, t_steps, nx, ny), dtype=np.float32))
        f.create_dataset("t0_fields/tracer", data=np.zeros((1, t_steps, nx, ny), dtype=np.float32))

    # Test full resolution dataset
    ds_full = ShearFlowDataset(
        file_paths=[str(h5_path)],
        history_length=2,
        horizon=2,
        downsample_factor=1,
    )
    sample = ds_full[0]
    hist = sample["history"]  # (2, 4, Nx, Ny)
    assert hist.shape == (2, 4, nx, ny), f"Expected shape (2, 4, {nx}, {ny}), got {hist.shape}"

    # Verify channel 0 is u (varies across axis -2 = x)
    u_tensor = hist[0, 0]  # (64, 128)
    assert u_tensor.shape == (nx, ny)
    # Along y (axis -1), u should be constant across columns
    assert torch.allclose(u_tensor[:, 0], u_tensor[:, 1], atol=1e-5)

    # Verify channel 1 is v (varies across axis -1 = y)
    v_tensor = hist[0, 1]
    assert v_tensor.shape == (nx, ny)
    # Along x (axis -2), v should be constant across rows
    assert torch.allclose(v_tensor[0, :], v_tensor[1, :], atol=1e-5)

    # Test downsampled dataset
    ds_down = ShearFlowDataset(
        file_paths=[str(h5_path)],
        history_length=2,
        horizon=2,
        downsample_factor=2,
    )
    sample_down = ds_down[0]
    hist_down = sample_down["history"]
    assert hist_down.shape == (2, 4, nx // 2, ny // 2)


def test_analytical_divergence_free_streamfunction():
    """Test 2: Analytical divergence-free velocity field generated by streamfunction psi.

    psi(x, y) = sin(2*pi*x / Lx) * sin(2*pi*y / Ly)
    For Lx = 1.0, Ly = 2.0:
    psi(x, y) = sin(2*pi*x) * sin(pi*y)
    u =  d(psi)/dy =  pi * sin(2*pi*x) * cos(pi*y)
    v = -d(psi)/dx = -2*pi * cos(2*pi*x) * sin(pi*y)

    div = du/dx + dv/dy = 2*pi^2 * cos(2*pi*x) * cos(pi*y) - 2*pi^2 * cos(2*pi*x) * cos(pi*y) = 0.
    """
    nx, ny = 128, 256
    lx, ly = 1.0, 2.0

    x = torch.linspace(0.0, 1.0 - lx / nx, nx, dtype=torch.float64)
    y = torch.linspace(0.0, 2.0 - ly / ny, ny, dtype=torch.float64)
    xx, yy = torch.meshgrid(x, y, indexing="ij")  # shape: (nx, ny)

    u = torch.pi * torch.sin(2.0 * torch.pi * xx) * torch.cos(torch.pi * yy)
    v = -2.0 * torch.pi * torch.cos(2.0 * torch.pi * xx) * torch.sin(torch.pi * yy)

    # Spectral derivatives
    du_dx, du_dy = spectral_grad_2d(u.float(), domain_size=(lx, ly))
    dv_dx, dv_dy = spectral_grad_xy(v.float(), domain_size=(lx, ly))

    # Analytical values
    exact_du_dx = 2.0 * (torch.pi ** 2) * torch.cos(2.0 * torch.pi * xx) * torch.cos(torch.pi * yy)
    exact_dv_dy = -2.0 * (torch.pi ** 2) * torch.cos(2.0 * torch.pi * xx) * torch.cos(torch.pi * yy)

    assert torch.norm(du_dx.double() - exact_du_dx) / torch.norm(exact_du_dx) < 1e-4
    assert torch.norm(dv_dy.double() - exact_dv_dy) / torch.norm(exact_dv_dy) < 1e-4

    # Divergence
    div = compute_divergence(u.float(), v.float(), domain_size=(lx, ly))
    assert torch.max(torch.abs(div)) < 5e-4
    assert torch.sqrt(torch.mean(div**2)) < 1e-4

    # DivergenceLoss
    q = torch.stack([u.float(), v.float(), torch.zeros_like(u.float()), torch.zeros_like(u.float())], dim=0).unsqueeze(0)
    loss_fn = DivergenceLoss(domain_size=(lx, ly))
    assert loss_fn(q).item() < 1e-7


def test_analytical_vorticity_and_laplacian():
    """Test 3: Analytical vorticity omega = dv/dx - du/dy = -laplacian(psi).

    For psi = sin(2*pi*x) * sin(pi*y):
    dv/dx = 4*pi^2 * sin(2*pi*x) * sin(pi*y)
    du_dy = -pi^2 * sin(2*pi*x) * sin(pi*y)
    omega = dv/dx - du/dy = 5*pi^2 * sin(2*pi*x) * sin(pi*y)
    lap(psi) = -(4*pi^2 + pi^2) * psi = -5*pi^2 * psi = -omega.
    """
    nx, ny = 128, 256
    lx, ly = 1.0, 2.0

    x = torch.linspace(0.0, 1.0 - lx / nx, nx, dtype=torch.float64)
    y = torch.linspace(0.0, 2.0 - ly / ny, ny, dtype=torch.float64)
    xx, yy = torch.meshgrid(x, y, indexing="ij")

    psi = torch.sin(2.0 * torch.pi * xx) * torch.sin(torch.pi * yy)
    u = torch.pi * torch.sin(2.0 * torch.pi * xx) * torch.cos(torch.pi * yy)
    v = -2.0 * torch.pi * torch.cos(2.0 * torch.pi * xx) * torch.sin(torch.pi * yy)

    exact_omega = 5.0 * (torch.pi ** 2) * psi

    omega_calc = compute_vorticity(u.float(), v.float(), domain_size=(lx, ly))
    err_vort = torch.norm(omega_calc.double() - exact_omega) / torch.norm(exact_omega)
    assert err_vort < 5e-4

    lap_psi = compute_laplacian_2d(psi.float(), domain_size=(lx, ly))
    err_lap = torch.norm(lap_psi.double() + exact_omega) / torch.norm(exact_omega)
    assert err_lap < 5e-4


def test_real_gt_incompressibility_sanity():
    """Test 4: Verify real Ground Truth data incompressibility under corrected operator.

    Under the exact pre-R4 implementation (which swapped domain_size to (2.0, 1.0) and computed
    du/d(axis -1) + dv/d(axis -2)), the downsampled GT divergence RMSE was 1.785469.
    Under the corrected Closure-R4 operator, the downsampled GT divergence RMSE drops to 0.001926
    (a 99.89% error reduction).
    """
    real_hdf5 = "/root/autodl-tmp/datasets/shear_flow/data/valid/shear_flow_Reynolds_1e4_Schmidt_1e-1.hdf5"
    if not os.path.exists(real_hdf5):
        pytest.skip(f"Real HDF5 dataset not present at {real_hdf5}")

    with h5py.File(real_hdf5, "r") as f:
        vel = f["t1_fields/velocity"][0, 10]  # (256, 512, 2)
        u_full = torch.from_numpy(vel[..., 0])
        v_full = torch.from_numpy(vel[..., 1])

    # Downsampled by 2 (model resolution 128 x 256)
    u_down = u_full[::2, ::2]
    v_down = v_full[::2, ::2]

    # 1. Correct divergence with canonical domain_size=(1.0, 2.0)
    div_corrected = compute_divergence(u_down, v_down, domain_size=(1.0, 2.0))
    div_rmse = torch.sqrt(torch.mean(div_corrected**2)).item()

    # 2. Exact old pre-R4 implementation:
    ny, nx = u_down.shape[-2], u_down.shape[-1]
    ly_old, lx_old = 2.0, 1.0
    ky_old = 2.0 * torch.pi * torch.fft.fftfreq(ny, d=ly_old / ny).view(ny, 1)
    kx_old = 2.0 * torch.pi * torch.fft.rfftfreq(nx, d=lx_old / nx).view(1, nx // 2 + 1)
    u_hat = torch.fft.rfft2(u_down.float(), dim=(-2, -1))
    v_hat = torch.fft.rfft2(v_down.float(), dim=(-2, -1))
    if nx % 2 == 0:
        u_hat[:, nx // 2] = 0.0
    if ny % 2 == 0:
        v_hat[ny // 2, :] = 0.0
    du_dx_old = torch.fft.irfft2(1j * kx_old * u_hat, s=(ny, nx), dim=(-2, -1))
    dv_dy_old = torch.fft.irfft2(1j * ky_old * v_hat, s=(ny, nx), dim=(-2, -1))
    div_old = du_dx_old + dv_dy_old
    div_old_rmse = torch.sqrt(torch.mean(div_old**2)).item()

    # Assertions
    assert div_rmse < 0.005, f"Real GT divergence RMSE should be < 0.005, got {div_rmse}"
    assert div_old_rmse > 1.5, f"Exact old swapped divergence RMSE should be > 1.5, got {div_old_rmse}"
    reduction = (div_old_rmse - div_rmse) / div_old_rmse
    assert reduction > 0.998, f"Divergence reduction should be > 99.8%, got {reduction * 100:.2f}%"
