"""Audit discrete PDE residuals across four representative operational regimes:

1. GT Full Resolution (256x512): Original published numerical dataset.
2. GT Model Resolution (128x256): Downsampled physical ground truth.
3. AE Reconstruction D(E(q_GT)): Physical fields reconstructed through frozen representation.
4. D0 Forecaster Rollout: Autonomous predictions generated by baseline Transformer.

Strict Contract Guarantees:
- Strict path resolution: Fails immediately if manifest path does not exist. No guessing or valid/ fallback.
- Strict trajectory indexing: Fails immediately if traj_idx >= n_sims. No modulo remapping (% n_sims).
- Identical evaluation intervals: All four levels evaluated across the exact same prediction horizon
  intervals (e.g. t_3 -> t_4, t_4 -> t_5, t_5 -> t_6, t_6 -> t_7) with explicitly defined q0 connection.
- Divergence computed strictly over the identical prediction frames (t = 4, 5, 6, 7).
- Fail-closed: Raises RuntimeError if sample_count == 0 (no fake zero metrics).
- Full provenance metadata: Archives evaluated files, trajectories, Re, Sc, dt, and model checkpoints.
"""

import hashlib
import json
import os
import subprocess
import sys
from typing import Any, Dict, List, Optional

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

import h5py
import numpy as np
import torch
import torch.nn as nn

from src.data.normalization import FieldNormalizer
from src.data.shear_flow_dataset import validate_uniform_time_grid
from src.losses.navier_stokes import NavierStokesPDELoss
from src.models.decoder import Decoder2D
from src.models.encoder import Encoder2D
from src.models.latent_transformer import LatentSTTransformer
from src.utils.fft_derivatives import compute_divergence


def compute_file_sha256(filepath: str) -> Optional[str]:
    """Compute SHA-256 hexadecimal digest for a file, or return None if not present."""
    if not os.path.exists(filepath):
        return None
    h = hashlib.sha256()
    with open(filepath, "rb") as f:
        while chunk := f.read(8192 * 1024):
            h.update(chunk)
    return h.hexdigest()


def get_git_commit_hash() -> str:
    """Retrieve current git commit hash for audit traceability."""
    try:
        out = subprocess.check_output(["git", "rev-parse", "HEAD"], stderr=subprocess.DEVNULL)
        return out.decode("utf-8").strip()
    except Exception:
        return "unknown"


def get_git_dirty() -> bool:
    """Check if the git working tree has uncommitted modifications."""
    try:
        out = subprocess.check_output(["git", "status", "--porcelain"], stderr=subprocess.DEVNULL)
        return len(out.strip()) > 0
    except Exception:
        return False


def precheck_audit_manifest_and_samples(
    split_file: str,
    data_root: str,
    total_window: int = 8,
    num_samples: Optional[int] = None,
) -> List[Dict[str, Any]]:
    """Strictly validate manifest integrity, file paths, trajectory indices, time grid, and fields.

    This function executes entirely before loading any model checkpoints or allocating GPU buffers,
    ensuring fail-fast data contract enforcement and complete test isolation in clean CI environments.

    Args:
        split_file: Path to JSON split manifest file.
        data_root: Directory root to resolve relative HDF5 file paths.
        total_window: Minimum contiguous time steps required per sample (history_length + horizon).
        num_samples: Optional cap on the number of samples to validate.

    Returns:
        List of validated sample records containing resolved file paths, indices, Re, Sc, and dt.

    Raises:
        FileNotFoundError: If split manifest or referenced HDF5 file is missing.
        ValueError: If manifest has no valid trajectories, or time grid is non-finite / irregular.
        IndexError: If trajectory index is negative or out of bounds (>= n_sims).
        KeyError: If required physics scalars or fields are missing.
        RuntimeError: If 0 samples are evaluated.
    """
    if not os.path.exists(split_file):
        raise FileNotFoundError(f"Split file '{split_file}' not found.")

    with open(split_file, "r") as f:
        splits = json.load(f)

    val_trajs = splits.get("valid", [])
    if not val_trajs:
        raise ValueError(f"No valid trajectories found in {split_file}")

    if num_samples is not None and num_samples <= 0:
        raise RuntimeError(
            f"Strict audit failure: num_samples={num_samples} must be > 0. "
            f"Failing closed to prevent writing unverified empty audit reports."
        )

    validated_samples: List[Dict[str, Any]] = []

    for traj_info in val_trajs:
        if num_samples is not None and len(validated_samples) >= num_samples:
            break

        h5_rel = traj_info.get("file_path")
        if not h5_rel:
            raise ValueError(f"Trajectory specification missing 'file_path': {traj_info}")

        sim_idx = traj_info.get("traj_idx")
        if sim_idx is None:
            raise ValueError(f"Trajectory specification missing 'traj_idx': {traj_info}")

        # Strict path resolution: NEVER guess, NEVER fallback to valid/
        h5_path = os.path.join(data_root, h5_rel) if not os.path.isabs(h5_rel) else h5_rel
        if not os.path.exists(h5_path):
            raise FileNotFoundError(
                f"Strict data contract violation: specified manifest file '{h5_rel}' not found at '{h5_path}'. "
                f"Directory guessing or fallback is forbidden."
            )

        with h5py.File(h5_path, "r") as f:
            if "t1_fields/velocity" not in f:
                raise KeyError(f"Missing 't1_fields/velocity' dataset in file '{h5_path}'.")
            vel_ds = f["t1_fields/velocity"]
            n_sims = vel_ds.shape[0]

            # Strict trajectory indexing: NEVER take modulo (% n_sims), enforce 0 <= traj_idx < n_sims
            if sim_idx < 0 or sim_idx >= n_sims:
                raise IndexError(
                    f"Strict data contract violation: requested traj_idx={sim_idx} out of range (expected 0 <= traj_idx < {n_sims}) "
                    f"in file '{h5_path}'. Modulo remapping is forbidden."
                )

            if "scalars/Reynolds" not in f or "scalars/Schmidt" not in f:
                raise KeyError(f"Physics scalar parameters missing in file '{h5_path}'.")
            re_val = float(f["scalars/Reynolds"][()])
            sc_val = float(f["scalars/Schmidt"][()])
            if not (np.isfinite(re_val) and re_val > 0):
                raise ValueError(f"Invalid non-positive or non-finite Re={re_val} in file '{h5_path}'.")
            if not (np.isfinite(sc_val) and sc_val > 0):
                raise ValueError(f"Invalid non-positive or non-finite Sc={sc_val} in file '{h5_path}'.")

            if "t0_fields/pressure" not in f or "t0_fields/tracer" not in f:
                raise KeyError(f"Required pressure or tracer fields missing in file '{h5_path}'.")

            # Strict time verification via unified validate_uniform_time_grid
            if "dimensions/time" not in f and "time" not in f:
                raise KeyError(f"Explicit time dataset missing in file '{h5_path}'. Fabricating dt is forbidden.")
            time_ds = f["dimensions/time"] if "dimensions/time" in f else f["time"]
            time_arr = np.asarray(time_ds, dtype=np.float64)

            dt_val = validate_uniform_time_grid(
                time_arr[:total_window],
                min_steps=total_window,
                source_desc=f"{h5_path} (traj {sim_idx})",
            )

            validated_samples.append({
                "file_path": h5_path,
                "rel_file_path": h5_rel,
                "traj_idx": sim_idx,
                "re": re_val,
                "sc": sc_val,
                "dt": dt_val,
            })

    if len(validated_samples) == 0:
        raise RuntimeError(
            f"Strict audit failure: 0 samples were evaluated from split '{split_file}'. "
            f"Failing closed to prevent writing unverified empty audit reports."
        )

    return validated_samples


def audit_pde_residuals(
    split_file: str = "outputs/splits/grouped_split.json",
    norm_file: str = "outputs/normalization/stats_grouped.pt",
    ae_ckpt: str = "outputs/checkpoints/representation/best_autoencoder.pt",
    d0_ckpt: str = "outputs/checkpoints/dynamics/horizon_r2/seed_42/E4_H12/latent_transformer/best_long_vrmse.pt",
    data_root: Optional[str] = None,
    num_samples: int = 4,
    horizon: int = 4,
    history_length: int = 4,
    output_json: str = "outputs/evaluations/pde_residual_audit.json",
    device: Optional[torch.device] = None,
) -> Dict[str, Any]:
    """Run discrete PDE residual audit strictly adhering to the evaluation contract."""
    if device is None:
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    if data_root is None:
        data_root = os.environ.get("SHEAR_FLOW_DATA_DIR", "/root/autodl-tmp/datasets/shear_flow")

    total_window = history_length + horizon

    # Precheck data manifest, file existence, bounds, time grid, and fields BEFORE loading weights
    print(f"Prechecking audit data manifest and samples from {split_file}...")
    validated_samples = precheck_audit_manifest_and_samples(
        split_file=split_file,
        data_root=data_root,
        total_window=total_window,
        num_samples=num_samples,
    )

    if not os.path.exists(norm_file):
        raise FileNotFoundError(f"Normalizer checkpoint '{norm_file}' not found.")
    if not os.path.exists(ae_ckpt):
        raise FileNotFoundError(f"Autoencoder checkpoint '{ae_ckpt}' not found.")
    if not os.path.exists(d0_ckpt):
        raise FileNotFoundError(f"D0 dynamics checkpoint '{d0_ckpt}' not found.")

    print(f"Loading normalizer from {norm_file}...")
    normalizer = FieldNormalizer()
    normalizer_state = torch.load(norm_file, map_location=device, weights_only=True)
    normalizer.load_state_dict(normalizer_state)
    normalizer.to(device)

    # 1. Load Autoencoder components
    print(f"Loading Autoencoder components from {ae_ckpt}...")
    encoder = Encoder2D(in_channels=4, latent_channels=64).to(device)
    decoder = Decoder2D(latent_channels=64, out_channels=4).to(device)
    ae_state = torch.load(ae_ckpt, map_location=device, weights_only=False)
    encoder.load_state_dict(ae_state["encoder_state_dict"])
    decoder.load_state_dict(ae_state["decoder_state_dict"])
    encoder.eval()
    decoder.eval()

    # 2. Load D0 Transformer & Unified Forecaster
    print(f"Loading D0 Forecaster from {d0_ckpt}...")
    from scripts.train_forecaster import LatentForecasterWrapper

    d0_state = torch.load(d0_ckpt, map_location=device, weights_only=False)
    transformer = LatentSTTransformer(
        latent_channels=64,
        embed_dim=256,
        depth=6,
        num_heads=8,
        history_length=history_length,
        prediction_mode="direct",
    ).to(device)

    model = LatentForecasterWrapper(
        encoder=encoder,
        transformer=transformer,
        decoder=decoder,
        freeze_representation=True,
    ).to(device)

    model.load_state_dict(d0_state["model_state_dict"])
    model.eval()

    pde_loss_full = NavierStokesPDELoss(domain_size=(1.0, 2.0), dealias=True).to(device)
    pde_loss_model = NavierStokesPDELoss(domain_size=(1.0, 2.0), dealias=True).to(device)

    levels = ["1_gt_full", "2_gt_downsampled", "3_ae_reconstruction", "4_d0_prediction"]
    accumulators: Dict[str, Dict[str, List[float]]] = {
        lvl: {"div_rmse": [], "res_u_rmse": [], "res_v_rmse": [], "res_s_rmse": []}
        for lvl in levels
    }

    evaluated_samples_meta: List[Dict[str, Any]] = []
    total_window = history_length + horizon
    sample_count = 0

    print(f"Auditing discrete PDE residuals on {num_samples} validation samples...")
    print(f"Contract: History L={history_length} (frames 0..{history_length - 1}), Horizon H={horizon} (frames {history_length}..{total_window - 1})")
    print(f"Transition intervals: {history_length - 1}->{history_length} up to {total_window - 2}->{total_window - 1} ({horizon} intervals)")

    with torch.no_grad():
        for sample_info in validated_samples:
            h5_path = sample_info["file_path"]
            sim_idx = sample_info["traj_idx"]
            re_val = sample_info["re"]
            sc_val = sample_info["sc"]
            dt_val = sample_info["dt"]

            with h5py.File(h5_path, "r") as f:
                vel = f["t1_fields/velocity"][sim_idx, :total_window]  # (T, 256, 512, 2)
                p = f["t0_fields/pressure"][sim_idx, :total_window]    # (T, 256, 512)
                s = f["t0_fields/tracer"][sim_idx, :total_window]      # (T, 256, 512)

                u_full = vel[..., 0]
                v_full = vel[..., 1]
                q_full_np = np.stack([u_full, v_full, p, s], axis=1)  # (T, 4, 256, 512)

            q_full = torch.from_numpy(q_full_np).float().to(device).unsqueeze(0)  # (1, T, 4, 256, 512)
            q_down = q_full[..., ::2, ::2]  # (1, T, 4, 128, 256)

            # Slices strictly aligned to prediction horizon H:
            # history frames: 0 .. history_length - 1
            # connection frame q0: index history_length - 1 (t = 3)
            # prediction frames: history_length .. total_window - 1 (t = 4, 5, 6, 7)
            # transition intervals: 3->4, 4->5, 5->6, 6->7 (exactly 4 intervals)
            q0_idx = history_length - 1
            pred_slice = slice(history_length, total_window)

            q0_full = q_full[:, q0_idx]
            q_full_pred = q_full[:, pred_slice]

            q0_down = q_down[:, q0_idx]
            q_down_pred = q_down[:, pred_slice]

            # ----------------------------------------------------
            # Level 1: GT Full Resolution (256x512)
            # ----------------------------------------------------
            div_full = compute_divergence(q_full_pred[0, :, 0], q_full_pred[0, :, 1], domain_size=(1.0, 2.0))
            div_full_rmse = torch.sqrt(torch.mean(div_full**2)).item()
            _, stats_full = pde_loss_full(
                q_full_pred,
                re=re_val,
                sc=sc_val,
                dt=dt_val,
                q0_phys=q0_full,
            )
            accumulators["1_gt_full"]["div_rmse"].append(div_full_rmse)
            accumulators["1_gt_full"]["res_u_rmse"].append(stats_full["res_momentum_u_rmse"])
            accumulators["1_gt_full"]["res_v_rmse"].append(stats_full["res_momentum_v_rmse"])
            accumulators["1_gt_full"]["res_s_rmse"].append(stats_full["res_tracer_s_rmse"])

            # ----------------------------------------------------
            # Level 2: GT Model Resolution (128x256)
            # ----------------------------------------------------
            div_down = compute_divergence(q_down_pred[0, :, 0], q_down_pred[0, :, 1], domain_size=(1.0, 2.0))
            div_down_rmse = torch.sqrt(torch.mean(div_down**2)).item()
            _, stats_down = pde_loss_model(
                q_down_pred,
                re=re_val,
                sc=sc_val,
                dt=dt_val,
                q0_phys=q0_down,
            )
            accumulators["2_gt_downsampled"]["div_rmse"].append(div_down_rmse)
            accumulators["2_gt_downsampled"]["res_u_rmse"].append(stats_down["res_momentum_u_rmse"])
            accumulators["2_gt_downsampled"]["res_v_rmse"].append(stats_down["res_momentum_v_rmse"])
            accumulators["2_gt_downsampled"]["res_s_rmse"].append(stats_down["res_tracer_s_rmse"])

            # ----------------------------------------------------
            # Level 3: AE Reconstruction D(E(q_down)) (128x256)
            # ----------------------------------------------------
            q_down_norm = normalizer.normalize(q_down)
            z_down = encoder(q_down_norm)
            q_recon_norm = decoder(z_down)
            q_recon = normalizer.denormalize(q_recon_norm)

            q0_recon = q_recon[:, q0_idx]
            q_recon_pred = q_recon[:, pred_slice]

            div_recon = compute_divergence(q_recon_pred[0, :, 0], q_recon_pred[0, :, 1], domain_size=(1.0, 2.0))
            div_recon_rmse = torch.sqrt(torch.mean(div_recon**2)).item()
            _, stats_recon = pde_loss_model(
                q_recon_pred,
                re=re_val,
                sc=sc_val,
                dt=dt_val,
                q0_phys=q0_recon,
            )
            accumulators["3_ae_reconstruction"]["div_rmse"].append(div_recon_rmse)
            accumulators["3_ae_reconstruction"]["res_u_rmse"].append(stats_recon["res_momentum_u_rmse"])
            accumulators["3_ae_reconstruction"]["res_v_rmse"].append(stats_recon["res_momentum_v_rmse"])
            accumulators["3_ae_reconstruction"]["res_s_rmse"].append(stats_recon["res_tracer_s_rmse"])

            # ----------------------------------------------------
            # Level 4: D0 Forecaster Rollout (128x256)
            # ----------------------------------------------------
            q_hist_norm = q_down_norm[:, :history_length]
            re_tensor = torch.tensor([re_val], device=device, dtype=torch.float32)
            sc_tensor = torch.tensor([sc_val], device=device, dtype=torch.float32)

            q_pred_norm = model.forward_rollout(
                q_hist_norm,
                re=re_tensor,
                sc=sc_tensor,
                horizon=horizon,
            )
            q_pred = normalizer.denormalize(q_pred_norm)

            div_pred = compute_divergence(q_pred[0, :, 0], q_pred[0, :, 1], domain_size=(1.0, 2.0))
            div_pred_rmse = torch.sqrt(torch.mean(div_pred**2)).item()
            _, stats_pred = pde_loss_model(
                q_pred,
                re=re_val,
                sc=sc_val,
                dt=dt_val,
                q0_phys=q0_down,
            )
            accumulators["4_d0_prediction"]["div_rmse"].append(div_pred_rmse)
            accumulators["4_d0_prediction"]["res_u_rmse"].append(stats_pred["res_momentum_u_rmse"])
            accumulators["4_d0_prediction"]["res_v_rmse"].append(stats_pred["res_momentum_v_rmse"])
            accumulators["4_d0_prediction"]["res_s_rmse"].append(stats_pred["res_tracer_s_rmse"])

            sample_meta = {
                "sample_idx": sample_count,
                "file_path": h5_path,
                "traj_idx": sim_idx,
                "re": re_val,
                "sc": sc_val,
                "dt": dt_val,
                "evaluated_intervals": f"{q0_idx}->{history_length} to {total_window - 2}->{total_window - 1}",
            }
            evaluated_samples_meta.append(sample_meta)
            sample_count += 1

    # Strict fail-closed: If no samples were evaluated, fail immediately
    if sample_count == 0:
        raise RuntimeError(
            f"Strict audit failure: 0 samples were evaluated from split '{split_file}'. "
            f"Failing closed to prevent writing unverified empty audit reports."
        )

    # Summarize results
    results: Dict[str, Dict[str, float]] = {}
    print("\n" + "=" * 90)
    print(f"PDE DISCRETE RESIDUAL AUDIT SUMMARY (Mean across {sample_count} verified samples)")
    print(f"Evaluation window: exactly matched horizon H={horizon} intervals ({history_length - 1}->{history_length} .. {total_window - 2}->{total_window - 1})")
    print("=" * 90)
    print(f"{'Operational Level':<25} | {'Div RMSE':<10} | {'Res_u RMSE':<12} | {'Res_v RMSE':<12} | {'Res_s RMSE':<12}")
    print("-" * 90)

    for lvl in levels:
        results[lvl] = {
            metric: float(np.mean(vals))
            for metric, vals in accumulators[lvl].items()
        }
        print(
            f"{lvl:<25} | "
            f"{results[lvl]['div_rmse']:<10.4e} | "
            f"{results[lvl]['res_u_rmse']:<12.4e} | "
            f"{results[lvl]['res_v_rmse']:<12.4e} | "
            f"{results[lvl]['res_s_rmse']:<12.4e}"
        )
    print("=" * 90)

    script_file = os.path.abspath(__file__)
    audit_payload = {
        "metadata": {
            "git_commit": get_git_commit_hash(),
            "git_dirty": get_git_dirty(),
            "audit_script": os.path.relpath(script_file, os.getcwd()) if script_file.startswith(os.getcwd()) else script_file,
            "audit_script_sha256": compute_file_sha256(script_file),
            "dealias_protocol": (
                "Orszag 2/3 rule: projection P to 2/3 Nyquist cutoff with zeroed Nyquist mode "
                "before and after nonlinear multiplication, time difference using projected velocity"
            ),
            "split_file": split_file,
            "split_file_sha256": compute_file_sha256(split_file),
            "norm_file": norm_file,
            "norm_file_sha256": compute_file_sha256(norm_file),
            "ae_ckpt": ae_ckpt,
            "ae_ckpt_sha256": compute_file_sha256(ae_ckpt),
            "d0_ckpt": d0_ckpt,
            "d0_ckpt_sha256": compute_file_sha256(d0_ckpt),
            "history_length": history_length,
            "horizon": horizon,
            "total_window": total_window,
            "sample_count": sample_count,
            "evaluation_intervals": f"{history_length - 1}->{history_length} to {total_window - 2}->{total_window - 1}",
            "evaluated_samples": evaluated_samples_meta,
        },
        "results": results,
    }

    os.makedirs(os.path.dirname(output_json), exist_ok=True)
    with open(output_json, "w") as f:
        json.dump(audit_payload, f, indent=2)
    print(f"Audit results and complete provenance metadata written to {output_json}")

    return audit_payload


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Audit discrete PDE residuals across operational levels.")
    parser.add_argument("--output_json", type=str, default="outputs/evaluations/pde_residual_audit_traceable.json")
    parser.add_argument("--num_samples", type=int, default=4)
    args = parser.parse_args()
    audit_pde_residuals(output_json=args.output_json, num_samples=args.num_samples)
