"""Audit discrete PDE residuals across four representative operational regimes:

1. GT Full Resolution (256x512): Original published numerical dataset.
2. GT Model Resolution (128x256): Downsampled physical ground truth.
3. AE Reconstruction D(E(q_GT)): Physical fields reconstructed through frozen representation.
4. D0 Forecaster Rollout: Autonomous predictions generated by baseline Transformer.

Strict Contract Guarantees:
- Strict path resolution: Fails immediately if manifest path does not exist. No guessing or valid/ fallback.
- Strict trajectory indexing: Fails immediately if traj_idx >= n_sims. No modulo remapping (% n_sims).
- Identical evaluation intervals: All four levels evaluated across the exact same prediction horizon
  intervals (e.g. t_3 -> t_4, t_4 -> t_5, t_5 -> t_6, t_6 -> t_7) with explicitly defined q0 connection.
- Divergence computed strictly over the identical prediction frames (t = 4, 5, 6, 7).
- Fail-closed: Raises RuntimeError if sample_count == 0 (no fake zero metrics).
- Full provenance metadata: Archives evaluated files, trajectories, Re, Sc, dt, and model checkpoints.
"""

import json
import os
import sys
from typing import Any, Dict, List, Optional

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

import h5py
import numpy as np
import torch
import torch.nn as nn

from src.data.normalization import FieldNormalizer
from src.losses.navier_stokes import NavierStokesPDELoss
from src.models.decoder import Decoder2D
from src.models.encoder import Encoder2D
from src.models.latent_transformer import LatentSTTransformer
from src.utils.fft_derivatives import compute_divergence


def audit_pde_residuals(
    split_file: str = "outputs/splits/grouped_split.json",
    norm_file: str = "outputs/normalization/stats_grouped.pt",
    ae_ckpt: str = "outputs/checkpoints/representation/best_autoencoder.pt",
    d0_ckpt: str = "outputs/checkpoints/dynamics/horizon_r2/seed_42/E4_H12/latent_transformer/best_long_vrmse.pt",
    data_root: Optional[str] = None,
    num_samples: int = 4,
    horizon: int = 4,
    history_length: int = 4,
    output_json: str = "outputs/evaluations/pde_residual_audit.json",
    device: Optional[torch.device] = None,
) -> Dict[str, Any]:
    """Run discrete PDE residual audit strictly adhering to the evaluation contract."""
    if device is None:
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    if data_root is None:
        data_root = os.environ.get("SHEAR_FLOW_DATA_DIR", "/root/autodl-tmp/datasets/shear_flow")

    if not os.path.exists(split_file):
        raise FileNotFoundError(f"Split file '{split_file}' not found.")
    if not os.path.exists(norm_file):
        raise FileNotFoundError(f"Normalizer checkpoint '{norm_file}' not found.")
    if not os.path.exists(ae_ckpt):
        raise FileNotFoundError(f"Autoencoder checkpoint '{ae_ckpt}' not found.")
    if not os.path.exists(d0_ckpt):
        raise FileNotFoundError(f"D0 dynamics checkpoint '{d0_ckpt}' not found.")

    print(f"Loading data splits from {split_file}...")
    with open(split_file, "r") as f:
        splits = json.load(f)
    val_trajs = splits.get("valid", [])
    if not val_trajs:
        raise ValueError(f"No valid trajectories found in {split_file}")

    print(f"Loading normalizer from {norm_file}...")
    normalizer = FieldNormalizer()
    normalizer_state = torch.load(norm_file, map_location=device, weights_only=True)
    normalizer.load_state_dict(normalizer_state)
    normalizer.to(device)

    # 1. Load Autoencoder components
    print(f"Loading Autoencoder components from {ae_ckpt}...")
    encoder = Encoder2D(in_channels=4, latent_channels=64).to(device)
    decoder = Decoder2D(latent_channels=64, out_channels=4).to(device)
    ae_state = torch.load(ae_ckpt, map_location=device, weights_only=False)
    encoder.load_state_dict(ae_state["encoder_state_dict"])
    decoder.load_state_dict(ae_state["decoder_state_dict"])
    encoder.eval()
    decoder.eval()

    # 2. Load D0 Transformer & Unified Forecaster
    print(f"Loading D0 Forecaster from {d0_ckpt}...")
    from scripts.train_forecaster import LatentForecasterWrapper

    d0_state = torch.load(d0_ckpt, map_location=device, weights_only=False)
    transformer = LatentSTTransformer(
        latent_channels=64,
        embed_dim=256,
        depth=6,
        num_heads=8,
        history_length=history_length,
        prediction_mode="direct",
    ).to(device)

    model = LatentForecasterWrapper(
        encoder=encoder,
        transformer=transformer,
        decoder=decoder,
        freeze_representation=True,
    ).to(device)

    model.load_state_dict(d0_state["model_state_dict"])
    model.eval()

    pde_loss_full = NavierStokesPDELoss(domain_size=(1.0, 2.0), dealias=True).to(device)
    pde_loss_model = NavierStokesPDELoss(domain_size=(1.0, 2.0), dealias=True).to(device)

    levels = ["1_gt_full", "2_gt_downsampled", "3_ae_reconstruction", "4_d0_prediction"]
    accumulators: Dict[str, Dict[str, List[float]]] = {
        lvl: {"div_rmse": [], "res_u_rmse": [], "res_v_rmse": [], "res_s_rmse": []}
        for lvl in levels
    }

    evaluated_samples_meta: List[Dict[str, Any]] = []
    total_window = history_length + horizon
    sample_count = 0

    print(f"Auditing discrete PDE residuals on {num_samples} validation samples...")
    print(f"Contract: History L={history_length} (frames 0..{history_length - 1}), Horizon H={horizon} (frames {history_length}..{total_window - 1})")
    print(f"Transition intervals: {history_length - 1}->{history_length} up to {total_window - 2}->{total_window - 1} ({horizon} intervals)")

    with torch.no_grad():
        for traj_info in val_trajs:
            if sample_count >= num_samples:
                break

            h5_rel = traj_info["file_path"]
            sim_idx = traj_info["traj_idx"]

            # Strict path resolution: NEVER guess, NEVER fallback to valid/
            h5_path = os.path.join(data_root, h5_rel) if not os.path.isabs(h5_rel) else h5_rel
            if not os.path.exists(h5_path):
                raise FileNotFoundError(
                    f"Strict data contract violation: specified manifest file '{h5_rel}' not found at '{h5_path}'. "
                    f"Directory guessing or fallback is forbidden."
                )

            with h5py.File(h5_path, "r") as f:
                vel_ds = f["t1_fields/velocity"]
                n_sims = vel_ds.shape[0]

                # Strict trajectory indexing: NEVER take modulo (% n_sims)
                if sim_idx >= n_sims:
                    raise IndexError(
                        f"Strict data contract violation: requested traj_idx={sim_idx} exceeds available trajectories "
                        f"(n_sims={n_sims}) in file '{h5_path}'. Modulo remapping is forbidden."
                    )

                if "scalars/Reynolds" not in f or "scalars/Schmidt" not in f:
                    raise KeyError(f"Physics scalar parameters missing in file '{h5_path}'.")
                re_val = float(f["scalars/Reynolds"][()])
                sc_val = float(f["scalars/Schmidt"][()])

                # Strict time reading
                if "dimensions/time" not in f and "time" not in f:
                    raise KeyError(f"Explicit time dataset missing in file '{h5_path}'. Fabricating dt is forbidden.")
                time_ds = f["dimensions/time"] if "dimensions/time" in f else f["time"]
                time_arr = np.asarray(time_ds, dtype=np.float32)
                if len(time_arr) < total_window:
                    raise ValueError(f"Time dataset has length {len(time_arr)}, but window requires {total_window}.")
                dt_val = float(time_arr[1] - time_arr[0])
                if not (np.isfinite(dt_val) and dt_val > 0):
                    raise ValueError(f"Invalid non-positive or non-finite dt={dt_val} in file '{h5_path}'.")

                vel = vel_ds[sim_idx, :total_window]  # (T, 256, 512, 2)
                p = f["t0_fields/pressure"][sim_idx, :total_window]  # (T, 256, 512)
                s = f["t0_fields/tracer"][sim_idx, :total_window]    # (T, 256, 512)

                u_full = vel[..., 0]
                v_full = vel[..., 1]
                q_full_np = np.stack([u_full, v_full, p, s], axis=1)  # (T, 4, 256, 512)

            q_full = torch.from_numpy(q_full_np).float().to(device).unsqueeze(0)  # (1, T, 4, 256, 512)
            q_down = q_full[..., ::2, ::2]  # (1, T, 4, 128, 256)

            # Slices strictly aligned to prediction horizon H:
            # history frames: 0 .. history_length - 1
            # connection frame q0: index history_length - 1 (t = 3)
            # prediction frames: history_length .. total_window - 1 (t = 4, 5, 6, 7)
            # transition intervals: 3->4, 4->5, 5->6, 6->7 (exactly 4 intervals)
            q0_idx = history_length - 1
            pred_slice = slice(history_length, total_window)

            q0_full = q_full[:, q0_idx]
            q_full_pred = q_full[:, pred_slice]

            q0_down = q_down[:, q0_idx]
            q_down_pred = q_down[:, pred_slice]

            # ----------------------------------------------------
            # Level 1: GT Full Resolution (256x512)
            # ----------------------------------------------------
            div_full = compute_divergence(q_full_pred[0, :, 0], q_full_pred[0, :, 1], domain_size=(1.0, 2.0))
            div_full_rmse = torch.sqrt(torch.mean(div_full**2)).item()
            _, stats_full = pde_loss_full(
                q_full_pred,
                re=re_val,
                sc=sc_val,
                dt=dt_val,
                q0_phys=q0_full,
            )
            accumulators["1_gt_full"]["div_rmse"].append(div_full_rmse)
            accumulators["1_gt_full"]["res_u_rmse"].append(stats_full["res_momentum_u_rmse"])
            accumulators["1_gt_full"]["res_v_rmse"].append(stats_full["res_momentum_v_rmse"])
            accumulators["1_gt_full"]["res_s_rmse"].append(stats_full["res_tracer_s_rmse"])

            # ----------------------------------------------------
            # Level 2: GT Model Resolution (128x256)
            # ----------------------------------------------------
            div_down = compute_divergence(q_down_pred[0, :, 0], q_down_pred[0, :, 1], domain_size=(1.0, 2.0))
            div_down_rmse = torch.sqrt(torch.mean(div_down**2)).item()
            _, stats_down = pde_loss_model(
                q_down_pred,
                re=re_val,
                sc=sc_val,
                dt=dt_val,
                q0_phys=q0_down,
            )
            accumulators["2_gt_downsampled"]["div_rmse"].append(div_down_rmse)
            accumulators["2_gt_downsampled"]["res_u_rmse"].append(stats_down["res_momentum_u_rmse"])
            accumulators["2_gt_downsampled"]["res_v_rmse"].append(stats_down["res_momentum_v_rmse"])
            accumulators["2_gt_downsampled"]["res_s_rmse"].append(stats_down["res_tracer_s_rmse"])

            # ----------------------------------------------------
            # Level 3: AE Reconstruction D(E(q_down)) (128x256)
            # ----------------------------------------------------
            q_down_norm = normalizer.normalize(q_down)
            z_down = encoder(q_down_norm)
            q_recon_norm = decoder(z_down)
            q_recon = normalizer.denormalize(q_recon_norm)

            q0_recon = q_recon[:, q0_idx]
            q_recon_pred = q_recon[:, pred_slice]

            div_recon = compute_divergence(q_recon_pred[0, :, 0], q_recon_pred[0, :, 1], domain_size=(1.0, 2.0))
            div_recon_rmse = torch.sqrt(torch.mean(div_recon**2)).item()
            _, stats_recon = pde_loss_model(
                q_recon_pred,
                re=re_val,
                sc=sc_val,
                dt=dt_val,
                q0_phys=q0_recon,
            )
            accumulators["3_ae_reconstruction"]["div_rmse"].append(div_recon_rmse)
            accumulators["3_ae_reconstruction"]["res_u_rmse"].append(stats_recon["res_momentum_u_rmse"])
            accumulators["3_ae_reconstruction"]["res_v_rmse"].append(stats_recon["res_momentum_v_rmse"])
            accumulators["3_ae_reconstruction"]["res_s_rmse"].append(stats_recon["res_tracer_s_rmse"])

            # ----------------------------------------------------
            # Level 4: D0 Forecaster Rollout (128x256)
            # ----------------------------------------------------
            q_hist_norm = q_down_norm[:, :history_length]
            re_tensor = torch.tensor([re_val], device=device, dtype=torch.float32)
            sc_tensor = torch.tensor([sc_val], device=device, dtype=torch.float32)

            q_pred_norm = model.forward_rollout(
                q_hist_norm,
                re=re_tensor,
                sc=sc_tensor,
                horizon=horizon,
            )
            q_pred = normalizer.denormalize(q_pred_norm)

            div_pred = compute_divergence(q_pred[0, :, 0], q_pred[0, :, 1], domain_size=(1.0, 2.0))
            div_pred_rmse = torch.sqrt(torch.mean(div_pred**2)).item()
            _, stats_pred = pde_loss_model(
                q_pred,
                re=re_val,
                sc=sc_val,
                dt=dt_val,
                q0_phys=q0_down,
            )
            accumulators["4_d0_prediction"]["div_rmse"].append(div_pred_rmse)
            accumulators["4_d0_prediction"]["res_u_rmse"].append(stats_pred["res_momentum_u_rmse"])
            accumulators["4_d0_prediction"]["res_v_rmse"].append(stats_pred["res_momentum_v_rmse"])
            accumulators["4_d0_prediction"]["res_s_rmse"].append(stats_pred["res_tracer_s_rmse"])

            sample_meta = {
                "sample_idx": sample_count,
                "file_path": h5_path,
                "traj_idx": sim_idx,
                "re": re_val,
                "sc": sc_val,
                "dt": dt_val,
                "evaluated_intervals": f"{q0_idx}->{history_length} to {total_window - 2}->{total_window - 1}",
            }
            evaluated_samples_meta.append(sample_meta)
            sample_count += 1

    # Strict fail-closed: If no samples were evaluated, fail immediately
    if sample_count == 0:
        raise RuntimeError(
            f"Strict audit failure: 0 samples were evaluated from split '{split_file}'. "
            f"Failing closed to prevent writing unverified empty audit reports."
        )

    # Summarize results
    results: Dict[str, Dict[str, float]] = {}
    print("\n" + "=" * 90)
    print(f"PDE DISCRETE RESIDUAL AUDIT SUMMARY (Mean across {sample_count} verified samples)")
    print(f"Evaluation window: exactly matched horizon H={horizon} intervals ({history_length - 1}->{history_length} .. {total_window - 2}->{total_window - 1})")
    print("=" * 90)
    print(f"{'Operational Level':<25} | {'Div RMSE':<10} | {'Res_u RMSE':<12} | {'Res_v RMSE':<12} | {'Res_s RMSE':<12}")
    print("-" * 90)

    for lvl in levels:
        results[lvl] = {
            metric: float(np.mean(vals))
            for metric, vals in accumulators[lvl].items()
        }
        print(
            f"{lvl:<25} | "
            f"{results[lvl]['div_rmse']:<10.4e} | "
            f"{results[lvl]['res_u_rmse']:<12.4e} | "
            f"{results[lvl]['res_v_rmse']:<12.4e} | "
            f"{results[lvl]['res_s_rmse']:<12.4e}"
        )
    print("=" * 90)

    audit_payload = {
        "metadata": {
            "split_file": split_file,
            "norm_file": norm_file,
            "ae_ckpt": ae_ckpt,
            "d0_ckpt": d0_ckpt,
            "history_length": history_length,
            "horizon": horizon,
            "sample_count": sample_count,
            "evaluated_samples": evaluated_samples_meta,
        },
        "results": results,
    }

    os.makedirs(os.path.dirname(output_json), exist_ok=True)
    with open(output_json, "w") as f:
        json.dump(audit_payload, f, indent=2)
    print(f"Audit results and complete provenance metadata written to {output_json}")

    return audit_payload


if __name__ == "__main__":
    audit_pde_residuals()
