"""Audit discrete PDE residuals across four representative operational regimes:

1. GT Full Resolution (256x512): Original published numerical dataset.
2. GT Model Resolution (128x256): Downsampled physical ground truth.
3. AE Reconstruction D(E(q_GT)): Physical fields reconstructed through frozen representation.
4. D0 Forecaster Rollout: Autonomous predictions generated by baseline Transformer.

Computes:
- Divergence RMSE (div(u) = 0)
- Navier-Stokes momentum residual RMSE (r_u, r_v)
- Passive tracer advection-diffusion residual RMSE (r_s)
"""

import json
import os
import sys
from typing import Dict, List

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

import h5py
import numpy as np
import torch
import torch.nn as nn

from src.data.normalization import FieldNormalizer
from src.losses.navier_stokes import NavierStokesPDELoss
from src.models.decoder import Decoder2D
from src.models.encoder import Encoder2D
from src.models.history_buffer import HistoryBuffer
from src.models.latent_transformer import LatentSTTransformer
from src.utils.fft_derivatives import compute_divergence


def audit_pde_residuals(
    split_file: str = "outputs/splits/grouped_split.json",
    norm_file: str = "outputs/normalization/stats_grouped.pt",
    ae_ckpt: str = "outputs/checkpoints/representation/best_autoencoder.pt",
    d0_ckpt: str = "outputs/checkpoints/dynamics/horizon_r2/seed_42/E4_H12/latent_transformer/best_long_vrmse.pt",
    data_root: str = "/root/autodl-tmp/datasets/shear_flow/data",
    num_samples: int = 4,
    horizon: int = 4,
    history_length: int = 4,
    device: torch.device = torch.device("cuda" if torch.cuda.is_available() else "cpu"),
) -> Dict[str, Dict[str, float]]:
    """Run discrete PDE residual audit across the 4 operational levels."""
    print(f"Loading data splits from {split_file}...")
    with open(split_file, "r") as f:
        splits = json.load(f)
    val_trajs = splits.get("valid", [])
    if not val_trajs:
        raise ValueError(f"No valid trajectories found in {split_file}")

    print(f"Loading normalizer from {norm_file}...")
    normalizer = FieldNormalizer()
    normalizer_state = torch.load(norm_file, map_location=device)
    normalizer.load_state_dict(normalizer_state)
    normalizer.to(device)

    # 1. Load Autoencoder components
    print(f"Loading Autoencoder components from {ae_ckpt}...")
    encoder = Encoder2D(in_channels=4, latent_channels=64).to(device)
    decoder = Decoder2D(latent_channels=64, out_channels=4).to(device)
    ae_state = torch.load(ae_ckpt, map_location=device)
    encoder.load_state_dict(ae_state["encoder_state_dict"])
    decoder.load_state_dict(ae_state["decoder_state_dict"])
    encoder.eval()
    decoder.eval()

    # 2. Load D0 Transformer & Unified Forecaster
    print(f"Loading D0 Forecaster from {d0_ckpt}...")
    from scripts.train_forecaster import LatentForecasterWrapper

    d0_state = torch.load(d0_ckpt, map_location=device)
    transformer = LatentSTTransformer(
        latent_channels=64,
        embed_dim=256,
        depth=6,
        num_heads=8,
        history_length=history_length,
        prediction_mode="direct",
    ).to(device)

    model = LatentForecasterWrapper(
        encoder=encoder,
        transformer=transformer,
        decoder=decoder,
        freeze_representation=True,
    ).to(device)

    model.load_state_dict(d0_state["model_state_dict"])
    model.eval()

    pde_loss_full = NavierStokesPDELoss(domain_size=(1.0, 2.0), dealias=True).to(device)
    pde_loss_model = NavierStokesPDELoss(domain_size=(1.0, 2.0), dealias=True).to(device)

    levels = ["1_gt_full", "2_gt_downsampled", "3_ae_reconstruction", "4_d0_prediction"]
    accumulators: Dict[str, Dict[str, List[float]]] = {
        lvl: {"div_rmse": [], "res_u_rmse": [], "res_v_rmse": [], "res_s_rmse": []}
        for lvl in levels
    }

    total_window = history_length + horizon
    sample_count = 0

    with torch.no_grad():
        for traj_info in val_trajs:
            if sample_count >= num_samples:
                break

            h5_rel = traj_info["file_path"]
            sim_idx = traj_info["traj_idx"]
            h5_path = os.path.join(data_root, h5_rel) if not os.path.isabs(h5_rel) else h5_rel
            if not os.path.exists(h5_path):
                # Fallback to search in valid/
                fname = os.path.basename(h5_rel)
                h5_path = os.path.join(data_root, "valid", fname)
                if not os.path.exists(h5_path):
                    continue

            with h5py.File(h5_path, "r") as f:
                re_val = float(f["scalars/Reynolds"][()])
                sc_val = float(f["scalars/Schmidt"][()])
                dt_val = float(f["dimensions/time"][1] - f["dimensions/time"][0]) if "dimensions/time" in f else 0.1

                vel_ds = f["t1_fields/velocity"]
                n_sims = vel_ds.shape[0]
                actual_sim = sim_idx % n_sims

                vel = vel_ds[actual_sim, :total_window]  # (T, 256, 512, 2)
                p = f["t0_fields/pressure"][actual_sim, :total_window]    # (T, 256, 512)
                s = f["t0_fields/tracer"][actual_sim, :total_window]      # (T, 256, 512)

                u_full = vel[..., 0]
                v_full = vel[..., 1]
                q_full_np = np.stack([u_full, v_full, p, s], axis=1)  # (T, 4, 256, 512)

            q_full = torch.from_numpy(q_full_np).float().to(device).unsqueeze(0)  # (1, T, 4, 256, 512)
            q_down = q_full[..., ::2, ::2]  # (1, T, 4, 128, 256)

            # Evaluate Level 1: GT Full Resolution
            div_full = compute_divergence(q_full[0, :, 0], q_full[0, :, 1], domain_size=(1.0, 2.0))
            div_full_rmse = torch.sqrt(torch.mean(div_full**2)).item()
            _, stats_full = pde_loss_full(
                q_full[:, 1:],
                re=re_val,
                sc=sc_val,
                dt=dt_val,
                q0_phys=q_full[:, 0],
            )
            accumulators["1_gt_full"]["div_rmse"].append(div_full_rmse)
            accumulators["1_gt_full"]["res_u_rmse"].append(stats_full["res_momentum_u_rmse"])
            accumulators["1_gt_full"]["res_v_rmse"].append(stats_full["res_momentum_v_rmse"])
            accumulators["1_gt_full"]["res_s_rmse"].append(stats_full["res_tracer_s_rmse"])

            # Evaluate Level 2: GT Model Resolution (128x256)
            div_down = compute_divergence(q_down[0, :, 0], q_down[0, :, 1], domain_size=(1.0, 2.0))
            div_down_rmse = torch.sqrt(torch.mean(div_down**2)).item()
            _, stats_down = pde_loss_model(
                q_down[:, 1:],
                re=re_val,
                sc=sc_val,
                dt=dt_val,
                q0_phys=q_down[:, 0],
            )
            accumulators["2_gt_downsampled"]["div_rmse"].append(div_down_rmse)
            accumulators["2_gt_downsampled"]["res_u_rmse"].append(stats_down["res_momentum_u_rmse"])
            accumulators["2_gt_downsampled"]["res_v_rmse"].append(stats_down["res_momentum_v_rmse"])
            accumulators["2_gt_downsampled"]["res_s_rmse"].append(stats_down["res_tracer_s_rmse"])

            # Evaluate Level 3: AE Reconstruction D(E(q_down))
            q_down_norm = normalizer.normalize(q_down)
            z_down = encoder(q_down_norm)
            q_recon_norm = decoder(z_down)
            q_recon = normalizer.denormalize(q_recon_norm)

            div_recon = compute_divergence(q_recon[0, :, 0], q_recon[0, :, 1], domain_size=(1.0, 2.0))
            div_recon_rmse = torch.sqrt(torch.mean(div_recon**2)).item()
            _, stats_recon = pde_loss_model(
                q_recon[:, 1:],
                re=re_val,
                sc=sc_val,
                dt=dt_val,
                q0_phys=q_recon[:, 0],
            )
            accumulators["3_ae_reconstruction"]["div_rmse"].append(div_recon_rmse)
            accumulators["3_ae_reconstruction"]["res_u_rmse"].append(stats_recon["res_momentum_u_rmse"])
            accumulators["3_ae_reconstruction"]["res_v_rmse"].append(stats_recon["res_momentum_v_rmse"])
            accumulators["3_ae_reconstruction"]["res_s_rmse"].append(stats_recon["res_tracer_s_rmse"])

            # Evaluate Level 4: D0 Forecaster Rollout
            q_hist_norm = q_down_norm[:, :history_length]
            re_tensor = torch.tensor([re_val], device=device, dtype=torch.float32)
            sc_tensor = torch.tensor([sc_val], device=device, dtype=torch.float32)

            q_pred_norm = model.forward_rollout(
                q_hist_norm,
                re=re_tensor,
                sc=sc_tensor,
                horizon=horizon,
            )
            q_pred = normalizer.denormalize(q_pred_norm)

            div_pred = compute_divergence(q_pred[0, :, 0], q_pred[0, :, 1], domain_size=(1.0, 2.0))
            div_pred_rmse = torch.sqrt(torch.mean(div_pred**2)).item()
            _, stats_pred = pde_loss_model(
                q_pred,
                re=re_val,
                sc=sc_val,
                dt=dt_val,
                q0_phys=q_down[:, history_length - 1],
            )
            accumulators["4_d0_prediction"]["div_rmse"].append(div_pred_rmse)
            accumulators["4_d0_prediction"]["res_u_rmse"].append(stats_pred["res_momentum_u_rmse"])
            accumulators["4_d0_prediction"]["res_v_rmse"].append(stats_pred["res_momentum_v_rmse"])
            accumulators["4_d0_prediction"]["res_s_rmse"].append(stats_pred["res_tracer_s_rmse"])

            sample_count += 1

    # Summarize results
    results: Dict[str, Dict[str, float]] = {}
    print("\n" + "=" * 80)
    print("PDE DISCRETE RESIDUAL AUDIT SUMMARY (Mean RMSE across validation samples)")
    print("=" * 80)
    print(f"{'Operational Level':<25} | {'Div RMSE':<10} | {'Res_u RMSE':<12} | {'Res_v RMSE':<12} | {'Res_s RMSE':<12}")
    print("-" * 80)

    for lvl in levels:
        results[lvl] = {
            metric: float(np.mean(vals)) if len(vals) > 0 else 0.0
            for metric, vals in accumulators[lvl].items()
        }
        print(
            f"{lvl:<25} | "
            f"{results[lvl]['div_rmse']:<10.4e} | "
            f"{results[lvl]['res_u_rmse']:<12.4e} | "
            f"{results[lvl]['res_v_rmse']:<12.4e} | "
            f"{results[lvl]['res_s_rmse']:<12.4e}"
        )
    print("=" * 80)

    out_json = "outputs/evaluations/pde_residual_audit.json"
    os.makedirs(os.path.dirname(out_json), exist_ok=True)
    with open(out_json, "w") as f:
        json.dump(results, f, indent=2)
    print(f"Audit results written to {out_json}")

    return results


if __name__ == "__main__":
    audit_pde_residuals()
